from jinja2 import Template

def generate_report_html(scan):
    tmpl = Template("""
    <!DOCTYPE html>
    <html>
    <head><title>Recon Report – {{ scan.target }}</title>
    <style>
        body { font-family: 'Inter', system-ui, sans-serif; padding: 2rem; max-width: 900px; margin: auto; background: #0B1120; color: #F8FAFC; }
        h1 { color: #22D3EE; border-bottom: 2px solid #22D3EE; padding-bottom: 0.5rem; }
        .section { margin: 2rem 0; background: #111827; padding: 1.5rem; border-radius: 8px; }
        .section h2 { color: #22D3EE; }
        pre { background: #1E293B; padding: 1rem; border-radius: 4px; overflow: auto; }
        .badge { display: inline-block; padding: 0.2rem 0.8rem; border-radius: 20px; font-weight: bold; }
        .safe { background: #22C55E; color: #0B1120; }
        .unsafe { background: #EF4444; color: white; }
        .score-ring { text-align: center; margin: 1rem 0; }
        .score-ring .big { font-size: 3rem; font-weight: 700; color: #22D3EE; }
        .finding { border-left: 4px solid #22D3EE; padding-left: 1rem; margin: 1rem 0; }
        .finding.critical { border-left-color: #EF4444; }
        .finding.high { border-left-color: #F97316; }
        .finding.medium { border-left-color: #F59E0B; }
        .finding.low { border-left-color: #38BDF8; }
        .footer { margin-top: 3rem; text-align: center; color: #94A3B8; font-size: 0.9rem; }
    </style>
    </head>
    <body>
        <h1>🔍 RECON Security Assessment</h1>
        <p><strong>Target:</strong> {{ scan.target }}</p>
        <p><strong>Date:</strong> {{ scan.completed_at or scan.created_at }}</p>
        <p><strong>Status:</strong> {{ scan.status }}</p>

        {% if scan.results %}
        <div class="score-ring">
            <div class="big">{{ scan.results.score }}/100</div>
            <div style="font-size:1.2rem;">
                {% if scan.results.score >= 80 %}🟢 Excellent{% elif scan.results.score >= 60 %}🔵 Good{% elif scan.results.score >= 40 %}🟡 Warning{% else %}🔴 Critical{% endif %}
            </div>
        </div>

        <div class="section">
            <h2>Executive Summary</h2>
            <p>{{ scan.results.summary }}</p>
        </div>

        <div class="section">
            <h2>Risk Summary</h2>
            <ul>
            {% for f in scan.results.findings[:5] %}
                <li><strong>{{ f.severity }}:</strong> {{ f.title }}</li>
            {% endfor %}
            </ul>
        </div>

        <div class="section">
            <h2>Threat Intelligence</h2>
            <pre>{{ scan.results.safety_check | tojson(indent=2) }}</pre>
        </div>

        <div class="section">
            <h2>DNS Analysis</h2>
            <pre>{{ scan.results.dns | tojson(indent=2) }}</pre>
        </div>

        <div class="section">
            <h2>Network Exposure</h2>
            <pre>{{ scan.results.open_ports | tojson }}</pre>
        </div>

        <div class="section">
            <h2>HTTP Security</h2>
            <pre>{{ scan.results.http | tojson(indent=2) }}</pre>
        </div>

        <div class="section">
            <h2>Detailed Findings</h2>
            {% for f in scan.results.findings %}
            <div class="finding {{ f.severity.lower() }}">
                <strong>{{ f.severity }}:</strong> {{ f.title }}
                <p>{{ f.detail }}</p>
                <p><em>Evidence:</em> {{ f.evidence }}</p>
                <p><strong>Recommendation:</strong> {{ f.recommendation }}</p>
            </div>
            {% endfor %}
        </div>

        <div class="section">
            <h2>Technical Appendix</h2>
            <pre>{{ scan.results | tojson(indent=2) }}</pre>
        </div>
        {% endif %}

        <div class="footer">
            <p>Generated by RECON – for authorised use only.</p>
        </div>
    </body>
    </html>
    """)
    return tmpl.render(scan=scan)